Milestone 3: Game Logic
Elbie-em/OOP-Tic-Tac-Toe-Game pull request #6
Opened 2020-03-20 20:54 UTC by Elbie-em

-Applied Game logic with use of OOP concepts
  -Added Game Class
  -Added Player Class
  -Added Board Class
  -Updated main file to strictly be for user interaction

2020-03-20 21:41 UTC, shshamim63 requested changes
## Status :space_invader: Required Changes :space_invader: 
___
Hi @Elbie-em and @rsnazario :wave: ,
Great job. Your code looks neat and clean. Well indented code. But some issues are blocking me to approve this milestone now. So please read the issues mentioned below and resolve them to achieve your ultimate target.
___
### :spades: Mandatory Changes :spades: 
___
1. You should not change the configuration of the linter file.
2. No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). But I can see tons of that. So you have to fix those issues too.
3. You have to add the correct attribute accessor to the game class.
___
### :clubs: Optional Changes :clubs: 
___
1. There are tons of ways to refactor your code. The more you refactor your code it will be more concise. I have added some sample. Well, you can add those to modify your classes.
___
#### Please fix the above mentioned issue and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain
[Linkedin](https://www.linkedin.com/in/shakhawathossainshamim/) | [Twitter](https://twitter.com/Shshamim090)

2020-03-20 21:41 UTC, shshamim63 commented on .rubocop.yml
> +  Max: 1000
You should not override the default configurations. So instead of it, do inline disabling. Which will urge you to resolve the error later.

2020-03-20 21:41 UTC, shshamim63 commented on lib/board.rb
> +    puts " #{board[6]}|#{board[7]}|#{board[8]}".center(38)
No puts outside of main.rb. so you have to find a way to acquire this task.

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +    end
I think you can simplify this part by the code below.
```ruby
if index
  board[index] = param
end
```

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +    if board[position] == ' ' || board[position] == '' || board[position].nil?
you can refactor the code by using any? method like
```ruby
['', ' ', nil].any?(board[position])
```

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +        puts 'Please enter a number in range of 0-8'
No puts outside main.rb

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +        puts 'Invalid move, enter number in range of 0-8'
No puts in here

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +        puts puts "#{player.name}, that position is filled, Try again..."
No puts

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +    else
There is an easy way to refactor it. Think about 2d array. The solution is in there.

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +        option = gets.chomp
No p/puts or chomp

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +        p "#{@players[1].name}'s move"
No p/puts are allowed.

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +      puts
no p/puts are allowed

2020-03-20 21:41 UTC, shshamim63 commented on lib/board.rb
> +      p 'Error'
no p/puts outside of main.rb

2020-03-20 21:41 UTC, shshamim63 commented on lib/game.rb
> +  end
Need correct attribute accessor. But can not see any

2020-03-20 23:41 UTC, rsnazario commented
Hello TSE team, I have one important question.

Can we add for example a class named

 >class Interaction<

And apply the prints and gets inside it?
Should we apply it in the main as methods?
Should we apply it on the main without methods!?
Thank you.

Em sex, 20 de mar de 2020 18:41, Shakhawat Hossain <notifications@github.com>
escreveu:

> *@shshamim63* requested changes on this pull request.
> Status 👾 Required Changes 👾
> ------------------------------
>
> Hi @Elbie-em <https://github.com/Elbie-em> and @rsnazario
> <https://github.com/rsnazario> 👋 ,
> Great job. Your code looks neat and clean. Well indented code. But some
> issues are blocking me to approve this milestone now. So please read the
> issues mentioned below and resolve them to achieve your ultimate target.
> ------------------------------
> ♠️ Mandatory Changes ♠️
> ------------------------------
>
>    1. You should not change the configuration of the linter file.
>    2. No puts/print and get.chomp outside main.rb file. (screenshot
>    <https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png>
>    from Pathwright
>    <https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/>).
>    But I can see tons of that. So you have to fix those issues too.
>    3. You have to add the correct attribute accessor to the game class.
>
> ------------------------------
> ♣️ Optional Changes ♣️
> ------------------------------
>
>    1. There are tons of ways to refactor your code. The more you refactor
>    your code it will be more concise. I have added some sample. Well, you can
>    add those to modify your classes.
>
> ------------------------------
> Please fix the above mentioned issue and send another review request.
> ------------------------------
> 🌿 Happy Coding 🌿 Shakhawat Hossain
>
> Linkedin <https://www.linkedin.com/in/shakhawathossainshamim/> | Twitter
> <https://twitter.com/Shshamim090>
> ------------------------------
>
> In .rubocop.yml
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395894432>
> :
>
> > -  Max: 120
>
> +  Max: 500
>
>  Metrics/MethodLength:
>
> -  Max: 20
>
> -Metrics/AbcSize:
>
>    Max: 50
>
> +Metrics/AbcSize:
>
> +  Max: 200
>
>  Metrics/ClassLength:
>
> -  Max: 150
>
> +  Max: 1000
>
>
> You should not override the default configurations. So instead of it, do
> inline disabling. Which will urge you to resolve the error later.
> ------------------------------
>
> In lib/board.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395894821>
> :
>
> > +    puts " #{board[0]}|#{board[1]}|#{board[2]}".center(38)
>
> +    puts " #{board[3]}|#{board[4]}|#{board[5]}".center(38)
>
> +    puts " #{board[6]}|#{board[7]}|#{board[8]}".center(38)
>
>
> No puts outside of main.rb. so you have to find a way to acquire this task.
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395895504>
> :
>
> > +    case index
>
> +    when 0
>
> +      board[0] = param
>
> +    when 1
>
> +      board[1] = param
>
> +    when 2
>
> +      board[2] = param
>
> +    when 3
>
> +      board[3] = param
>
> +    when 4
>
> +      board[4] = param
>
> +    when 5
>
> +      board[5] = param
>
> +    when 6
>
> +      board[6] = param
>
> +    when 7
>
> +      board[7] = param
>
> +    when 8
>
> +      board[8] = param
>
> +    end
>
>
> I think you can simplify this part by the code below.
>
> if index
>
>   board[index] = param
> end
>
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395896751>
> :
>
> > +      board[3] = param
>
> +    when 4
>
> +      board[4] = param
>
> +    when 5
>
> +      board[5] = param
>
> +    when 6
>
> +      board[6] = param
>
> +    when 7
>
> +      board[7] = param
>
> +    when 8
>
> +      board[8] = param
>
> +    end
>
> +  end
>
> +
>
> +  def position_filled?(board, position)
>
> +    if board[position] == ' ' || board[position] == '' || board[position].nil?
>
>
> you can refactor the code by using any? method like
>
> ['', ' ', nil].any?(board[position])
>
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395896862>
> :
>
> > +      board[8] = param
>
> +    end
>
> +  end
>
> +
>
> +  def position_filled?(board, position)
>
> +    if board[position] == ' ' || board[position] == '' || board[position].nil?
>
> +      false
>
> +    else
>
> +      true
>
> +    end
>
> +  end
>
> +
>
> +  def in_range(move)
>
> +    loop do
>
> +      unless move.between?('0', '8')
>
> +        puts 'Please enter a number in range of 0-8'
>
>
> No puts outside main.rb
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395896947>
> :
>
> > +
>
> +  def in_range(move)
>
> +    loop do
>
> +      unless move.between?('0', '8')
>
> +        puts 'Please enter a number in range of 0-8'
>
> +        move = gets.chomp
>
> +      end
>
> +      break if move.between?('0', '8')
>
> +    end
>
> +    move.to_i
>
> +  end
>
> +
>
> +  def valid?(move)
>
> +    loop do
>
> +      if move.class != Integer || !move.between?(0, 8)
>
> +        puts 'Invalid move, enter number in range of 0-8'
>
>
> No puts in here
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395897073>
> :
>
> > +  def valid?(move)
>
> +    loop do
>
> +      if move.class != Integer || !move.between?(0, 8)
>
> +        puts 'Invalid move, enter number in range of 0-8'
>
> +        move = gets.chomp
>
> +        move = in_range(move)
>
> +      end
>
> +      break if move.class == Integer && move.between?(0, 8)
>
> +    end
>
> +    move
>
> +  end
>
> +
>
> +  def check_position(board, move, player)
>
> +    loop do
>
> +      if position_filled?(board, move)
>
> +        puts puts "#{player.name}, that position is filled, Try again..."
>
>
> No puts
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395897483>
> :
>
> > +    first_cmbn = [0, 1, 2]
>
> +    second_cmbn = [3, 4, 5]
>
> +    third_cmbn = [6, 7, 8]
>
> +    fourth_cmbn = [0, 3, 6]
>
> +    fifth_cmbn = [1, 4, 7]
>
> +    sixth_cmbn = [2, 5, 8]
>
> +    seventh_cmbn = [0, 4, 8]
>
> +    eighth_cmbn = [2, 4, 6]
>
> +
>
> +    board.each_with_index do |i, index|
>
> +      p1_move << index if i == 'X'
>
> +      p2_move << index if i == 'O'
>
> +    end
>
> +
>
> +    if (first_cmbn - p1_move).empty? || (second_cmbn - p1_move).empty? || (third_cmbn - p1_move).empty? || (fourth_cmbn - p1_move).empty? || (fifth_cmbn - p1_move).empty? || (sixth_cmbn - p1_move).empty? || (seventh_cmbn - p1_move).empty? || (eighth_cmbn - p1_move).empty?
>
> +      1
>
> +    elsif (first_cmbn - p2_move).empty? || (second_cmbn - p2_move).empty? || (third_cmbn - p2_move).empty? || (fourth_cmbn - p2_move).empty? || (fifth_cmbn - p2_move).empty? || (sixth_cmbn - p2_move).empty? || (seventh_cmbn - p2_move).empty? || (eighth_cmbn - p2_move).empty?
>
> +      2
>
> +    else
>
>
> There is an easy way to refactor it. Think about 2d array. The solution is
> in there.
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie-em/OOP-Tic-Tac-Toe-Game/pull/6#discussion_r395897828>
> :
>
> > +        count = 0
>
> +        print 'Loading'
>
> +        while count < 10
>
> +          print '.'
>
> +          count += 1
>
> +          sleep(0.1)
>
> +        end
>
> +        break
>
> +      elsif option === 'N'
>
> +        p 'Thank you. See you next time.'
>
> +        exit
>
> +      else
>
> +        p 'Wrong option! Please select Y or N.'
>
> +        option = gets.chomp
>
>
> No p/puts or chomp
> ------------------------------
>
> In lib/game.rb
> <https://github.com/Elbie- [...]

2020-03-22 19:35 UTC, Elbie-em commented
Hello TSE team, 

As Rafael has put, where do we place these methods, the sole purpose if you see is too encapsulate those validation methods and avoid the main file from being filled with repetitive. Those validations are called within the main game loop . So we would kindly request for advice on how to refactor these features in order for our project to be approved.

Your quick response will be highly appreciated

Thanks in advance

2020-03-23 19:05 UTC, pelzolga123 approved these changes
Approved.

2020-03-23 19:06 UTC, pelzolga123 commented
## Great  work, Congratulation :+1: Project Approved.
You did all changes required previously. Go ahead and merge to master.
_Goodluck in your next project_ *Happy coding*

2020-03-23 20:48 UTC, merged